### ISSUE TITLE
MainNet full node

### ISSUE THREAD

**Issue by ambertch** [OriginProtocol/origin-devops#12]
Along with the IPFS deployment, we are planning to run a MainNet full node. While we don't require a full node for current and planned operations, we could in the future and it may be good to gain experience operating one.

The full node can be added to Prometheus along with the IPFS servers.

**Comment by ambertch** [comment]
Nodes were set up for MainNet, Rinkeby, and Ropsten. As of this posting, the Rinkeby and Ropsten nodes are up to date with the most recent block, while the MainNet node seems to be syncing at a block every one or two seconds (`highestBlock` is the most recent block in the network).

```
  currentBlock: 6028874,
  highestBlock: 6100855,
```

**Comment by micahalcorn** [comment]
Cool @ambertch does that mean that we could potentially expect to get 12 block confirmations in under 20 seconds? I mean from our web3 callbacks - not necessarily related to our full node or indexing.

**Comment by ambertch** [comment]
Confirmations refer to the number of blocks that have been mined since the block a transaction is included in, which have the transaction's block as an ancestor. So a block confirmation happens in a block time, 12 confirmations take 12 block times.

When a full node starts up, it builds a blockchain from the genesis block until it catches up with the current block being mined in the network. This is the syncing rate that is being referred to.

**Comment by tomlinton** [comment]
Mainnet node is up and synced. It kept falling behind despite using SSDs but it just needed a bunch more memory allocated to it. Closing!
