### ISSUE TITLE
OrbitDB Server For Persistent Messaging

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-devops#14]
Making an issue so that we don't forget to prioritize this 🤞

**Comment by ambertch** [comment]
A server has been set up with pubsub and websocket, as well as the endpoints protected by HTTP authentication https://github.com/OriginProtocol/origin-devops/tree/server-setup/messaging

OrbitDB may also be added to the server

**Comment by ambertch** [comment]
The orbit code from https://github.com/OriginProtocol/origin-bridge/commit/8a476fd1d82a367707bad21ec78a89d61577eec0 was integrated into the server, with the README/playbook located at https://github.com/OriginProtocol/origin-devops/tree/server-setup/messaging
