### ISSUE TITLE
OrbitDB snapshotting for messaging server

### ISSUE THREAD

**Issue by ambertch** [OriginProtocol/origin-devops#17]
Snap shotting was added to the messaging codebase and should be added to the server https://github.com/OriginProtocol/origin-bridge/pull/128/commits/afbe2698ed8228b651fe6aa4f359c8d014ccbbf9

In addition, the initial integration took place before the messaging PR, and the server should use package.json and babel (https://github.com/OriginProtocol/origin-bridge/pull/124/files)

@crazybuster just wanted to confirm: there are hooks in the code for snapshotting/replication, so it does not require a cron job, it looks like?

**Comment by ambertch** [comment]
The server previously executed a modified version of the orbit server script, without es2015 syntax.

Along with updating the code used, the setup was converted to use babel and package.json so that the operationalized code is not different than the developed version.

Currently, the code is placed within the ansible repo and copied to the server. In the future, it could be packaged as part of a CI build, with a deploy pointing to that build artifact.

**Comment by micahalcorn** [comment]
Great, thanks @ambertch 🙏
