### ISSUE TITLE
Make pid files for processes that don't generate one by default

### ISSUE THREAD

**Issue by ambertch** [OriginProtocol/origin-devops#20]
The OS records process related metrics under the /proc/<pid>/folder. In order to have these available in the monitoring system, the pid of a running process must be known. This is typically done through a pid file, although not all processes (IPFS, running programs) generate pid files. 

Systemd does not generate pid files, although upstart does through start-stop-daemon and the same mechanism could be used in the current setup.

**Comment by tomlinton** [comment]
Closed as this no longer relevant due to move to Kubernetes.
