### ISSUE TITLE
Messaging over port 80/443

### ISSUE THREAD

**Issue by ambertch** [OriginProtocol/origin-devops#23]
In development and as deployed currently, the messaging server runs on a dedicated websocket port. Because corporate and institutional internal firewalls may restrict outbound traffic to ports 80 and 443, it might be best for messaging to work over those ports.

- IPFS addresses are a 'multiaddr' which can encapsulate protocols within one another (see section 3.2.1 https://ipfs.io/ipfs/QmR7GSQM93Cx5eAg6a6yRzNde1FQv7uL6X1o4k7zrJa3LX/ipfs.draft3.pdf), and the current webrtc relay's address looks like ` /dns4/wrtc-star.discovery.libp2p.io/tcp/443/wss/p2p-webrtc-star`
- An IPFS multiaddr used to directly connect to an IPFS daemon looks like `/ip4/<ip>/tcp/<port>/ws/ipfs/<ipfs peerID>`
- If using SSL, SSL will terminate at nginx and then become a websocket connection to IPFS, so we may have to use a multiaddr with encapsulation (ex. `/ip4/<ip>/tcp/443/ws/ipfs/<ipfs peerID>`)

**Comment by crazybuster** [comment]
That seems good to me. Keep in mind I think wss is actual SSL vs ws is just a raw websocket connection. But if we want wss we need certs for the domain, so I think keeping it ws is fine.

**Comment by ambertch** [comment]
Gotcha. My thinking was to try on port 80 to see what the right multiaddr format was, then use SSL. The original gateway used certbot (which is free of cost https://certbot.eff.org/), it was posted yesterday that their CA is now universally supported (https://news.ycombinator.com/item?id=17698264)

**Comment by ambertch** [comment]
The persistence server IP was linked to messaging.originprotocol.com and a certificate was obtained from Certbot. One thing to note for the multiaddr is that while those of IPs start with `/ipv4/`, a multiaddr for a domain name starts with `/dnsaddr/`
