### ISSUE TITLE
Messaging: Keepalive

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-devops#27]
The DApp currently loses its WebSocket connection, which causes a variety of problems for the messaging feature. As long as the DApp is open in a browser, the connection should be maintained. This task will require adding some code to the client, preferably in [origin-js](https://github.com/OriginProtocol/origin-js/blob/develop/src/resources/messaging.js#L241), but it may have to go in [origin-dapp](https://github.com/OriginProtocol/origin-dapp/blob/develop/src/services/origin.js#L49).

**Comment by micahalcorn** [comment]
This may no longer be necessary with the inclusion of https://github.com/OriginProtocol/origin-js/commit/4c5a12610ea6ed08796ecf93daf6b581114e70bc#diff-3148f229ad8f5a9b6f74baa6cbdc2136 as a fallback if, in fact, Nginx is no longer killing the connection per @crazybuster.

**Comment by tomlinton** [comment]
I think it was probably nginx timeouts not being set appropriately for websockets. They are 60s by default, but It looks like they are updated in the current server and it’s been taken care of in the new deployment. With the reconnect as well we should be set. 👍

**Comment by micahalcorn** [comment]
@crazybuster I'm still unable to leave my browser open for an extended period of time and let messages roll in. I'm not sure what the symptom is, so I'll try to report back here next time I can check the console. The issue is that, since I can't be notified when I have a new message, I have to refresh my browser periodically and don't remember to do it.
