### ISSUE TITLE
Messaging: Server Crashing

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-devops#28]
Correct me if I'm wrong, but I believe that we need to diagnose an unknown issue with [the Orbit server](https://github.com/OriginProtocol/origin-bridge/blob/develop/js/messaging/orbit_server.js) crashing.

**Comment by tomlinton** [comment]
The messaging server has been running for a few days without crashing in the new Kubernetes setup, but it is not being used at the moment. I'm going to close this because the new setup is so different that the issue might not exist anymore. Will reopen if we run into it again.
