### ISSUE TITLE
Messaging: Systemd Hanging

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-devops#29]
If I understand correctly, we have a problem with systemd hanging when it tries to stop or restart [the Orbit server](https://github.com/OriginProtocol/origin-bridge/blob/develop/js/messaging/orbit_server.js) - related to #28?

**Comment by ambertch** [comment]
In the persistence server's package.json, npx is used to run local node module binaries (https://github.com/OriginProtocol/origin-bridge/blob/master/package.json#L11). In particular, babel is used to transpile es6 code into javascript.

The behavior of npx seems to be that it spawns a child process that runs the module using node:
```
ubuntu@messaging:~$ ps -ef | grep node
ubuntu   12595     1  0 23:14 ?        00:00:00 node /usr/bin/npx babel-node js/messaging/orbit_server.js
ubuntu   12607 12595 42 23:14 ?        00:00:11 /usr/bin/node /opt/orbit/node_modules/babel-cli/lib/_babel-node js/messaging/orbit_server.js
```

Although afterwards, only the child process remains:
```
ubuntu@messaging:~$ ps -ef | grep node
ubuntu   12607     1 10 23:14 ?        00:00:12 /usr/bin/node /opt/orbit/node_modules/babel-cli/lib/_babel-node js/messaging/orbit_server.js

```

Notice that the child process now has the same PID as the parent PID. It's likely that when systemd goes to stop the persistence server it is expecting to find the original npx process, but that is no longer there and so it doesn't know how to stop the server process.

One solution is to just directly invoke the command that npx invokes: `/usr/bin/node /opt/orbit/node_modules/babel-cli/lib/_babel-node js/messaging/orbit_server.js`

A caveat of this is that if the start command in package.json is changed, the command passed to systemd to execute would have to be changed as well. Although I'm not sure if there's a cleaner solution. In the event that the start command is changed in package.json but not in the server, it would be immediately detectable that the wrong command was being executed, so the error case is fairly mild.

**Comment by crazybuster** [comment]
There's also nodemon which might make things cleaner.

**Comment by tomlinton** [comment]
Closing this as systemd will not be used anymore.
